baseURL = "https://goldfish0506.github.io/"
languageCode = "en"
DefaultContentLanguage = "zh"
author = "Kim"
paginate = 20
ignoreErrors = ["error-remote-getjson"]
enableInlineShortcodes = true

title = "🔭 人间指南"
theme = "paper"

[params]
  color = 'linen'
  twitter = 'Goldfish0506'
  github = 'Goldfish0506'
  rss = true

  avatar = 'goldfish.jinyu@gmail.com'
  name = '主编 Kim'
  bio = '将自己的精神，注入产品与文字中'
  
  # misc
  disableHLJS = true
  math = true            
  monoDarkIcon = true

# 配置网站菜单
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10
