baseURL = "goldfish0506.github.io"
languageCode = "zh-CN"
title = "Kims Blog"
theme = "paper"

[params]
  color = 'linen'
  twitter = 'Goldfish0506'
  github = 'Goldfish0506'
  rss = true

  avatar = 'goldfish.jinyu@gmail.com'
  name = 'Kim'
  bio = '暴躁的金鱼'
  
  # misc
  disableHLJS = true
  math = true            
  monoDarkIcon = true

